### PR TITLE
Changes to produce additional release artefact with Shenandoah enabled

### LINKED ISSUE #11: Produce additional release artefact with Shenandoah enabled
The default JDK 11u build won't compile Shenandoah GC into the libjvm.so library. We should produce an additional artefact which comes with Shenandoah GC enabled so that interested parties can get it from our release Github page.

When Shenandoah GC is not available it looks like this:

```
$ java -XX:+UseShenandoahGC -version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

When Shenandoah GC has been compiled in this looks like:

```
$ java -XX:+UseShenandoahGC -version
openjdk version "11.0.10-internal" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10-internal+0-adhoc.sgehwolf.openjdk-11-dev)
OpenJDK 64-Bit Server VM (build 11.0.10-internal+0-adhoc.sgehwolf.openjdk-11-dev, mixed mode)
```

The relevant configure option to use is:

```
--with-jvm-features=shenandoagc
```

### PR DESCRIPTION
**Pull request by jhuttana**
@jerboaa Could you please review the changes and let me know the comments?

Veified the build and looks it is as expected.

1.
**Config without: --with-jvm-features=shenandoah
**Build artefact dir is 'release'
./java -XX:+UseShenandoahGC -version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

2.
**Config with --with-jvm-features=shenandoah
**Build artefact dir is 'shenandoah'
./java -XX:+UseShenandoahGC -version
openjdk version "11.0.9-ea" 2020-10-20
OpenJDK Runtime Environment 18.9 (build 11.0.9-ea+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9-ea+10, mixed mode)

3.
ls 
OpenJDK11U-sources_11.0.9_10_ea.tar.gz  release  shenandoah  slowdebug

Thank you!

### CODE REVIEW

File: build-openjdk11.sh [hunk 1]
```diff
@@ -34,6 +34,8 @@ TARBALL_VERSION="${UPDATE}_${BUILD}${EA_SUFFIX}"
 PLATFORM_VERSION="${PLATFORM}_${TARBALL_VERSION}"
 TARBALL_NAME="${TARBALL_BASE_NAME}-jdk_${PLATFORM_VERSION}"
 TARBALL_NAME_JRE="${TARBALL_BASE_NAME}-jre_${PLATFORM_VERSION}"
+TARBALL_NAME_SHENDOH="${TARBALL_BASE_NAME}-jdk-shenandoah_${PLATFORM_VERSION}"
+TARBALL_NAME_SHENDOH_JRE="${TARBALL_BASE_NAME}-jre-shenandoah_${PLATFORM_VERSION}"
```
Comment (jerboaa) [inline build-openjdk11.sh]: `TARBALL_NAME_SHENDOH` seems odd. Could we use `TARBALL_NAME_SHENANDOAH` instead for clarity, please?

File: install-rhel-deps-build-openjdk11.sh [hunk 2]
```diff
@@ -117,6 +117,8 @@ TARBALL_VERSION="\${UPDATE}_\${BUILD}\${EA_SUFFIX}"
 PLATFORM_VERSION="\${PLATFORM}_\${TARBALL_VERSION}"
 TARBALL_NAME="\${TARBALL_BASE_NAME}-jdk_\${PLATFORM_VERSION}"
 TARBALL_NAME_JRE="\${TARBALL_BASE_NAME}-jre_\${PLATFORM_VERSION}"
+TARBALL_NAME_SHENDOH="\${TARBALL_BASE_NAME}-jdk-shenandoah_\${PLATFORM_VERSION}"
+TARBALL_NAME_SHENDOH_JRE="\${TARBALL_BASE_NAME}-jre-shenandoah_\${PLATFORM_VERSION}"
 TARBALL_NAME_TEST_IMAGE="\${TARBALL_BASE_NAME}-testimage_\${PLATFORM_VERSION}"
```
Comment (jerboaa) [inline install-rhel-deps-build-openjdk11.sh:145]: We should perhaps have a testimage artefact ready too for shenandoah. Just in case.

File: install-rhel-deps-build-openjdk11.sh [hunk 3]
```diff
@@ -117,6 +117,8 @@ TARBALL_VERSION="\${UPDATE}_\${BUILD}\${EA_SUFFIX}"
 PLATFORM_VERSION="\${PLATFORM}_\${TARBALL_VERSION}"
 TARBALL_NAME="\${TARBALL_BASE_NAME}-jdk_\${PLATFORM_VERSION}"
 TARBALL_NAME_JRE="\${TARBALL_BASE_NAME}-jre_\${PLATFORM_VERSION}"
+TARBALL_NAME_SHENDOH="\${TARBALL_BASE_NAME}-jdk-shenandoah_\${PLATFORM_VERSION}"
```
Comment (jerboaa) [inline install-rhel-deps-build-openjdk11.sh]: Same `TARBALL_NAME_SHENDOH` comment. Either `TARBALL_NAME_SHGC` or `TARBALL_NAME_SHENANDOAH`

**Review by jerboaa — CHANGES_REQUESTED** [review]
This is mostly good. Only a few minor things. Nice work! Note: We'll wait with merging this until after 11.0.9 goes out.

File: install-rhel-deps-build-openjdk11.sh (hunk 3 above)
Comment (jhuttana) [reply install-rhel-deps-build-openjdk11.sh]: Addressed the above comments and given a build in parallel. I will update again once the build is done.

**Comment by jhuttana** [comment]
@jerboaa , build with recent changes is successful.
Could you please review?

**1.release artefacts**
$pwd
/home/openjdk/jdk11u/build/release/images

$ ls  *.tar.gz
OpenJDK11U-jdk_aarch64_linux_11.0.9_10_ea-debuginfo.tar.gz  
OpenJDK11U-jre_aarch64_linux_11.0.9_10_ea-debuginfo.tar.gz  
OpenJDK11U-static-libs_aarch64_linux_11.0.9_10_ea.tar.gz
OpenJDK11U-jdk_aarch64_linux_11.0.9_10_ea.tar.gz          
OpenJDK11U-jre_aarch64_linux_11.0.9_10_ea.tar.gz           
OpenJDK11U-testimage_aarch64_linux_11.0.9_10_ea.tar.gz

$./jdk/bin/java -XX:+UseShenandoahGC -version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**2.shenandoah artefacts**
$ pwd
/home/openjdk/jdk11u/build/shenandoah/images

$ ls  *.tar.gz
OpenJDK11U-jdk-shenandoah_aarch64_linux_11.0.9_10_ea-debuginfo.tar.gz  
OpenJDK11U-jre-shenandoah_aarch64_linux_11.0.9_10_ea-debuginfo.tar.gz  
OpenJDK11U-static-libs_aarch64_linux_11.0.9_10_ea.tar.gz
OpenJDK11U-jdk-shenandoah_aarch64_linux_11.0.9_10_ea.tar.gz            
OpenJDK11U-jre-shenandoah_aarch64_linux_11.0.9_10_ea.tar.gz            
OpenJDK11U-testimage-shenandoah_aarch64_linux_11.0.9_10_ea.tar.gz

$./jdk/bin/java -XX:+UseShenandoahGC -version
openjdk version "11.0.9-ea" 2020-10-20
OpenJDK Runtime Environment 18.9 (build 11.0.9-ea+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9-ea+10, mixed mode)

**Review by jerboaa — APPROVED** [review]
Looks fine to me. Thanks! We'll merge after the October CPU.

**Comment by jhuttana** [comment]
Okay. Thank you!
